keys:
  - &users
    - &tyw CB77A3AB52E22C93CA8EC5D1F6CDC71FFDBE2EC3

  - &system
    - &nix age1jq4sym7mp6ep9qc3wgc9p0utffasj5vt83a2jw4nkx5p8llyppxqf6fkh9

  - &hosts
    - &procurer-in-yeg age1fr8pfca48cnnu8pupumtdtcugzlxsffgdhywzcvu2t7e39kc6vaqqmtedq
    - &rokh-in-sea age1kdrpl2nqvav43jvr49qcttjsvjjlrt50rdxurd7hkc80hj5jd97s7353gl

creation_rules:
  - path_regex: home/secrets.*
    key_groups:
    - age:
      - *nix
      pgp:
      - *tyw
  - path_regex: hosts/secrets.*
    key_groups:
    - age:
        *hosts
      pgp:
      - *tyw
  # per host rules
  - path_regex: hosts/z/procurer-in-yeg/secrets.*
    key_groups:
    - age:
      - *procurer-in-yeg
      pgp:
      - *tyw
  - path_regex: hosts/z/rokh-in-sea/secrets.*
    key_groups:
    - age:
      - *rokh-in-sea
      pgp:
      - *tyw