data: ENC[AES256_GCM,data:0jwSZAeYBfiBwZ0lyAuXR2N2jwqIJsZQjRqhmDIRzfH8JQsnPDLlhDKSMl8=,iv:I11PbBaGaTcXhcB9qCJI8kJMvDLgqb/orL2Vz4AJqKM=,tag:Gu6V4ua0z1RjVMVtCdXhsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fr8pfca48cnnu8pupumtdtcugzlxsffgdhywzcvu2t7e39kc6vaqqmtedq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycXJBV1VEblBoRE05NWNi
            dExOeEpobTRXbGJNNUkvZnRpMEdsckw4U0NVClhlWHNnKzlBblhrbDQxakZWSnRU
            QmdyQVV4Ly9jRjdYTU5STC9ScXV2YkUKLS0tIFdoUWhCZU14eWdmc0h1d01QVExm
            alFPSTQ5eVEwVjNaeXFOdDYyR1pvZk0KZA2JwquPxl74fTuOTQZqGVon2ywDkHLo
            QjTt2oRfsv1FcFgnLkb495bIXoGlxUGnRr2p1fISyXkWf5wPpcQgwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdrpl2nqvav43jvr49qcttjsvjjlrt50rdxurd7hkc80hj5jd97s7353gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SFdjY0tlWk1yUDBZaFoz
            cjZoTlVyWHRoeHdTVWdKU1JaSDc4SkNiNEVBCnNHNnB5RExBY25CNXZpVTZ3MnpH
            NjYxaERyK1BvMjJzQXR0MUZGSEN1MncKLS0tIFlXK0Q0UmhkZDUyL1phaTFxd3ZS
            cXF6MDB2QTNzK2JteU1nb2d6T2FLY2sKUvyYSFueJnvb0bP7G6hGdtPg05zne1+f
            WGCGWw+PAcCiC917ZLVnK8rJMJ66D/k0fKnC0BKE5PE2D7CGtFzQ8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wr4v6d7ajx3e67lt2delkqqvd966tqqt67aq8dkm0ducxlhnupdqlyql0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbE5QRmx1WFJXdk5rUDlx
            R3pqQ3lkWWJFc0Rkb3lvYlJTdWErRnFIbFVNClF3TXJSUDArN0t3eEdBMmhVc3Fi
            ZDQvZ0NGMXpyZGJLK3RXd3hRNzl2MDAKLS0tIGJLaUVhcm94UEpVMmFoYWFzMEVI
            ajBDVDFLSUlOSTdPRDkzUUMxaFNtU2MKLnzqlxh+Mjk0X8EPirCtpJCbpOB3KWcs
            aDgFss6MaYCKSoLu2fq3xLdfa5nXZoNdUjOrK4QWOoASpXv1s9Wqyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T06:14:05Z"
    mac: ENC[AES256_GCM,data:pZuKxqUuWrW5s8obcBLE3zeI13hx1R0vphtquafEACwFnL/4YfmbzhAfrq6MXGQa7JsadcRQWnDmoe63NZ09hlSCb3sJJi5H6P65Co50JAojlyEb03JgDUMV7CTzp/4GebdOfOarj/iKIwi8u7/PyvGSWVYUk7WkOiqb8HvJM38=,iv:i+JjFyOZvuVFGI+JTu0dcv/83L9oyAW6DKFlQfJYaGQ=,tag:zYQ0Ke7bJ69eI03amKo8gQ==,type:str]
    pgp:
        - created_at: "2023-04-25T06:14:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DUxa2i9gPX+4SAQdAQoABhoTGTzeleV/6Kcl6ZG3fjcQYXe5emGs5LyHu1Hww
            YmmKL/0VqKbusAbPDBwIbTsqAQPLvs41IwYebTdX2K8Muc8TZW7MHoqhDUZ6E6ou
            0lEBOR46SIYdBXFJjIe7jRyj8cTuT9eLzGPrgyP3Tr5rYIMIQUaBLq9LklAW+C0r
            O8Y6eXdwNprrX047y3ENTaLLRt/kOGwvpBDvwj2jr47dF4o=
            =P8KM
            -----END PGP MESSAGE-----
          fp: CB77A3AB52E22C93CA8EC5D1F6CDC71FFDBE2EC3
    unencrypted_suffix: _unencrypted
    version: 3.7.3
