data: ENC[AES256_GCM,data:G4B+6p6MUYjEYTOdMbigS5dYLk31EnLEhuTcGM5+jjhgCJOoIircK1F/Bc0=,iv:hrX7B/83XBcCY32lJ1IvVHUAwwM+CtTniKOUP2gJtyU=,tag:3Y++Z3S7W9zQLtfI+nmbxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fr8pfca48cnnu8pupumtdtcugzlxsffgdhywzcvu2t7e39kc6vaqqmtedq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMVpUcnNwVjhwbVQzTHQ1
            ZVB5V0lPUjVEeUF3VnhVN0lDODFxZ01XV2lVCk1IYnF0VWIyWkJmYWMyWlVHZm5C
            Qm1ZTGdLclZPSEtRaDcveUR4bzFHWTQKLS0tIGtJbUM0dXF4aG1HWnBCMTQ4VFN5
            WEorTjEzUndUQlJuK0lJMTBPK1dsNFkK4T2t7LhI+OmKOPn18PXXuVv8TvNgxQpl
            TTfN8VRoQOw8EaqsndeUqNKerFxGV3AHCfWKGrF05KniBLg7A7p3vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdrpl2nqvav43jvr49qcttjsvjjlrt50rdxurd7hkc80hj5jd97s7353gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPczhXMXZJdTRnZGJHUUR3
            SGdVMG9leE9jZ3hEcXBSQVZxUWZ0OU43UVdrCisrRmxNUExEVEtnbkVGYUQ1UTBI
            bU8yZVpGSFl2TW1oREgwRnlUVnljbU0KLS0tIEpzMXp4QWt6Tkw2QUdmNEdJbGVW
            ZndQblB3NVdCa1ZOY1RlckxXUVgya0EKpbyuMifprbNWmV7RjrlNX1e8/l4N6oPY
            LAnQSD6sleBy7yk8eRbN3YXndIrQ21eLB5F/nLI1RYKkXH3rXWF3ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T07:19:44Z"
    mac: ENC[AES256_GCM,data:5hilLwDGdZ3iM6jjjwccv+4ypU866CgkbsfauuEnu9CkUWC8KWP5GZTzPMva7j+LBlkkg2nB3GqdBfrrckCf9oCwIMB1a+WAelBwuDlp//RguCdIreT8bDwEhdoqIvOajYima/kyipAmKIzT1rzuCQvEK121hzoQ6luhjDoSO20=,iv:FRC6zU+mIvBUdd3MnKGeO65gOZxydI9Z5VxosDQysW4=,tag:opBwdqN8tw80X7CsTu4GoQ==,type:str]
    pgp:
        - created_at: "2023-03-27T07:19:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DUxa2i9gPX+4SAQdAAVuTbhMWXnzOrR7WOG4Xl064lM5Ljo9v17uOdBFyehQw
            aKALY1nW1zLcm4f45KO2UtIukXgmQMOwfXv3UH94N8bI/A13D1+mg5etW2H6q1lt
            0lEBCewCvyl/SEFA9Snl3Vux47CbK373EwpHJKBnNbEStJTiPvYh4JIbfSxtQbWU
            +rNGlh1Ha5kRsHhZKZob/vVZ9u4N9CnjW1/kiNn3BnjMI1w=
            =ner2
            -----END PGP MESSAGE-----
          fp: CB77A3AB52E22C93CA8EC5D1F6CDC71FFDBE2EC3
    unencrypted_suffix: _unencrypted
    version: 3.7.3
