name: Flake.lock Trigger

on:
  push:
    branches:
      - master
    paths:
      - 'flake.lock'

jobs:
  callTheTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: nx-direct
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/tywtyw2002/nx-direct/actions/workflows/build.yml/dispatches \
          --data '{"ref": "master"}'

      - name: wireproxy
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/tywtyw2002/wireproxy/actions/workflows/build.yml/dispatches \
          --data '{"ref": "z/flake"}'
