name: Format Nix Code

on:
  push:
    branches:
      - ci
      - 'ci/**'

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27
        with:
          nix_conf: |
            build-users-group =
            experimental-features = nix-command flakes

      - name: format nix
        run: |
          nix-env -iA alejandra nixpkgs-fmt -f https://github.com/tywtyw2002/nx-direct/tarball/nx
          alejandra ./
          nixpkgs-fmt ./

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(bot): nix auto fmt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          pr_allow_empty: false
          pr_draft: false
