name: Format Nix Code

on:
  push:
    paths:
      - "**.nix"
    branches:
      - ci
      - 'ci/**'

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: alejandra format
        continue-on-error: true
        run: nix-shell -p alejandra --run 'alejandra ./'
      - name: nixpkgs-fmt
        run: nix fmt

      - name: Commit and push changes
        run: |
          git commit -am "style(bot): nix auto fmt"

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          branch: pr/auto
          base: master
