name: Format Nix Code

on:
  push:
    paths:
      - "**.nix"
    branches-ignore:
      - master

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: alejandra format
        continue-on-error: true
        run: nix-shell -p alejandra --run 'alejandra ./'
      - name: nixpkgs-fmt
        run: nix fmt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(bot): nix auto fmt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          branch: pr/auto
          base: master
          
